version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy2
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - '3003:3003'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: 'postgres:14-alpine'
    container_name: pg
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: starter
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    ports:
       - '5432:5432'
    # volumes:
    #   - ./pg-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
       - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
